### ISSUE TITLE
Input/Output more than one kind of value

### ISSUE THREAD

**Issue by KonstantinVeljanovski** [rokups/ImNodes#1]
Hello,
I have a question about the I/O nodes.
I was wondering how can one get a output to match more types?
I tried something like this but it did not seem to work:
`{"ADD Vector3", []() -> MyNode* { return new MyNode("ADD Vector3",
	{ {"A",WN Position | Rotation | Scale},
          {"B",WN  Position | Rotation | Scale} },
	{ {"Output" ,WN Position |  Rotation | Scale} }); } }`

Am i doing something wrong or is it not yet implemented?

Thank you and sorry for the trouble.

**Comment by rokups** [comment]
If i understand it correctly you would like to connect two slots:
* Slot A where `kind` is something like `Rotation|Scale`
* Slot B where `kind` is something like `Position|Scale`
Provided that both slots have a common component `Scale`.

At the moment node types are matched by comparing `kind` with `==` so it is not possible to connect two slots whose kinds do not match 100%. Partial matching could be done if `kind` was checked as a bitmask, but that immediately imposes a limit on the number of different slot kinds (32 if `kind` was `unsigned` and 64 if `kind` was `unsigned long long`) which isnt something we want.

**Comment by KonstantinVeljanovski** [comment]
First thank you for the fast reply.
I'm trying to create a node that can take/output for example either a Position/Rotation/Scale based on what the incoming/outgoing node connection.

**Comment by rokups** [comment]
Now that i think of it sample is a bit confusing. Library was built around the idea of slots representing certain types in code. "Position" or "Rotation" are not types, but "Vector3" is, and it could encode both position and rotation.

Instead of doing `WN Position | Rotation | Scale` simply assign a unique non-zero integer value as `kind`, outputs will connect to inputs if both slots have same `kind`.
